import type { CanvasEdge, CanvasNode } from "./types";

export const SAMPLE_NODES: CanvasNode[] = [
  {
    id: "start",
    x: 80,
    y: 80,
    title: "Array nums: [2, 7, 11, 15]",
    subtitle: "Target: 9",
    shape: "rectangle",
    variant: "primary",
    icon: "🔢",
  },
  {
    id: "check",
    x: 320,
    y: 65,
    title: "target - nums[i]",
    subtitle: "In Map?",
    shape: "diamond",
    variant: "warning",
    width: 140,
    height: 140,
  },
  {
    id: "hashmap",
    x: 310,
    y: 280,
    title: "Hash Table map",
    subtitle: "Stores {num: index}",
    shape: "database",
    variant: "purple",
    width: 160,
    height: 90,
  },
  {
    id: "match",
    x: 560,
    y: 90,
    title: "Solution Found",
    subtitle: "Return [map.get(diff), i]",
    shape: "pill",
    variant: "success",
    icon: "✅",
    width: 170,
    height: 60,
  },
  {
    id: "loop",
    x: 80,
    y: 290,
    title: "Next Index i++",
    subtitle: "Pointer advanced",
    shape: "rounded",
    variant: "cyan",
    icon: "🔄",
    width: 150,
    height: 70,
  },
];

export const SAMPLE_EDGES: CanvasEdge[] = [
  {
    id: "e1",
    sourceNodeId: "start",
    targetNodeId: "check",
    sourcePort: "right",
    targetPort: "left",
    label: "i = 0",
    color: "#38bdf8",
    animated: true,
  },
  {
    id: "e2",
    sourceNodeId: "check",
    targetNodeId: "match",
    sourcePort: "right",
    targetPort: "left",
    label: "Yes",
    color: "#10b981",
    animated: true,
  },
  {
    id: "e3",
    sourceNodeId: "check",
    targetNodeId: "hashmap",
    sourcePort: "bottom",
    targetPort: "top",
    label: "No",
    color: "#a855f7",
  },
  {
    id: "e4",
    sourceNodeId: "hashmap",
    targetNodeId: "loop",
    sourcePort: "left",
    targetPort: "right",
    label: "put(val, i)",
    color: "#a855f7",
  },
  {
    id: "e5",
    sourceNodeId: "loop",
    targetNodeId: "start",
    sourcePort: "top",
    targetPort: "bottom",
    color: "#06b6d4",
    dashed: true,
  },
];
